-- MEU TREINO V2 - Supabase
create table public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  workout text not null,
  exercise text not null,
  sets jsonb not null,
  created_at timestamptz default now()
);

create table public.share_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token uuid not null unique,
  created_at timestamptz default now()
);

alter table public.workouts enable row level security;
alter table public.share_tokens enable row level security;

create policy "owner can manage workouts" on public.workouts
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

create policy "owner can manage share tokens" on public.share_tokens
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- O link de compartilhamento precisa conseguir consultar os dados do dono.
-- Para a V2 inicial, recomendamos usar uma Edge Function para validar o token
-- e devolver somente os dados. Não abra a tabela workouts para anon diretamente.
