-- MEU TREINO V2 - Supabase
create table if not exists public.workouts (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  date date not null,
  workout text not null,
  exercise text not null,
  sets jsonb not null,
  created_at timestamptz default now()
);

create table if not exists public.share_tokens (
  id bigint generated by default as identity primary key,
  user_id uuid not null references auth.users(id) on delete cascade,
  token uuid not null unique,
  created_at timestamptz default now()
);

alter table public.workouts enable row level security;
alter table public.share_tokens enable row level security;

drop policy if exists "owner can manage workouts" on public.workouts;
create policy "owner can manage workouts" on public.workouts
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

drop policy if exists "owner can manage share tokens" on public.share_tokens;
create policy "owner can manage share tokens" on public.share_tokens
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- O link de compartilhamento precisa conseguir consultar os dados do dono.
-- Para a V2 inicial, recomendamos usar uma Edge Function para validar o token
-- e devolver somente os dados. Não abra a tabela workouts para anon diretamente.

-- ============================================================
-- V2.2 — Espaço do personal: plano de treino editável pelo link
-- Rode este bloco no Supabase em: Project > SQL Editor > New query
-- ============================================================

create table if not exists public.plans (
  user_id uuid primary key references auth.users(id) on delete cascade,
  workouts jsonb not null,
  day_order jsonb not null default '["A","B","C"]'::jsonb,
  updated_at timestamptz default now()
);

alter table public.plans enable row level security;

drop policy if exists "owner can manage plan" on public.plans;
create policy "owner can manage plan" on public.plans
for all using (auth.uid() = user_id) with check (auth.uid() = user_id);

-- Lida pelo link compartilhado: devolve o plano de treino + histórico do dono do token.
-- security definer permite ignorar RLS aqui dentro, mas só depois de validar o token.
create or replace function public.get_shared_data(p_token uuid)
returns table(workouts jsonb, day_order jsonb, history jsonb)
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid;
  v_workouts jsonb;
  v_day_order jsonb;
begin
  select user_id into v_user from share_tokens where token = p_token;
  if v_user is null then
    raise exception 'invalid token';
  end if;

  select p.workouts, p.day_order into v_workouts, v_day_order
  from plans p where p.user_id = v_user;

  return query select
    coalesce(v_workouts, '{}'::jsonb),
    coalesce(v_day_order, '["A","B","C"]'::jsonb),
    coalesce((
      select jsonb_agg(jsonb_build_object('date', w.date, 'workout', w.workout, 'exercise', w.exercise, 'sets', w.sets) order by w.date desc)
      from workouts w where w.user_id = v_user
    ), '[]'::jsonb);
end;
$$;

-- Lida pelo link compartilhado: grava o novo plano de treino em nome do dono do token,
-- sem exigir que o personal tenha login.
create or replace function public.update_shared_plan(p_token uuid, p_workouts jsonb, p_day_order jsonb)
returns void
language plpgsql
security definer
set search_path = public
as $$
declare
  v_user uuid;
begin
  select user_id into v_user from share_tokens where token = p_token;
  if v_user is null then
    raise exception 'invalid token';
  end if;

  insert into plans (user_id, workouts, day_order, updated_at)
  values (v_user, p_workouts, p_day_order, now())
  on conflict (user_id) do update
    set workouts = excluded.workouts,
        day_order = excluded.day_order,
        updated_at = now();
end;
$$;

-- Libera a execução das duas funções para visitantes sem login (anon),
-- que é o papel usado pelo link compartilhado. O acesso continua controlado
-- pelo token, verificado dentro de cada função.
grant execute on function public.get_shared_data(uuid) to anon;
grant execute on function public.update_shared_plan(uuid, jsonb, jsonb) to anon;
